import { RiArrowDownLine } from '@remixicon/react';
import PreviewMotion from '@/components/preview-motion';
import AnimatedButton from '@/components/animated-button';
import SiteHeader from '@/components/site-header';
import SiteFooter from '@/components/site-footer';
export default function HomePage() {
 return <div className="venue-page"><PreviewMotion/><a className="skip-link" href="#main">Skip to content</a><SiteHeader/>
  <main id="main" className="venue-main">
   <section className="venue-hero"><div className="venue-kicker"><span>STR. GEORGE ENESCU 25</span><span>COFFEE. CULTURE. AFTER HOURS.</span></div><h1>A PLACE<br/>IN BETWEEN<span>.</span></h1><div className="venue-hero-image"><img src="/images/sound-house.png" alt="Monochrome sound-house crowd — a generated vision of a night together" data-venue-parallax/><span>SOUND HOUSE / BUCHAREST</span><a href="#menu" aria-label="Explore our menu"><RiArrowDownLine/></a></div><div className="venue-intro"><p>For the ones making noise.<br/>And the ones finding their people.</p><span>Music, art, ink, and the energy of the streets.<br/>Different scenes. One shared space.</span></div></section>
   <section id="menu" className="menu-wall"><div className="menu-wall-image"><img src="/images/kraken-wall.png" alt="The violet Urbanist kraken painted across a weathered concrete wall" data-wall-parallax/></div><div className="menu-wall-shade"/><div className="menu-wall-content"><span className="eyebrow">FOOD FOR THE SOUL / SOMETHING TO SIP</span><h2>FOLLOW<br/>YOUR<br/>APPETITE<span>.</span></h2><p>First coffee. Something good.<br/>One more reason to stay.</p><AnimatedButton href="/menu" variant="light" hoverText="Find your favourite">Explore the menu</AnimatedButton></div><div className="menu-wall-bottom"><span>SPECIALTY COFFEE / FOOD / DRINKS</span><span>ORDER AT THE BAR. TALK TO OUR PEOPLE.</span></div></section>
   <section id="sound" className="venue-section sound-section"><span className="eyebrow">01 / SOUND</span><div className="venue-section-title"><h2>FOLLOW<br/>THE SOUND.</h2><p>From the first record to the last track.<br/>A space for live sessions, selectors,<br/>and the people who come to listen.</p></div><div className="sound-material"><img src="/images/five-bar-steel.png" alt="Five-bar silver tread plate" loading="lazy"/><strong>GOOD PEOPLE.<br/>LOUD NIGHTS.</strong></div><div className="sound-follow"><p>The next session. The next selector.<br/>Find out what’s happening on our Instagram.</p><AnimatedButton href="https://www.instagram.com/theurbanistbucharest/" external variant="outline" hoverText="Stay in the loop">What’s happening</AnimatedButton></div></section>
   <section id="culture" className="venue-section culture-section"><span className="eyebrow">02 / CULTURE</span><div className="venue-section-title"><h2>NO SINGLE<br/>FREQUENCY.</h2><div><p>Tattoo artists. Writers. Rappers. Skaters.<br/>People who make the city their own.</p><p>Come for your scene.<br/>Stay for everything in between.</p></div></div><div className="culture-words"><span>SOUND</span><span>ART</span><span>STREET</span><span>COMMUNITY</span></div></section>
   <section id="visit" className="venue-section visit-section"><span className="eyebrow">03 / THE PLACE</span><div className="venue-section-title"><h2>YOU KNOW<br/>WHERE.</h2><div><p>Urbanist Sound House<br/>Str. George Enescu nr. 25<br/>Bucharest, Romania</p><AnimatedButton href="https://www.google.com/maps/search/?api=1&query=The+Urbanist+Strada+George+Enescu+25+Bucharest" external hoverText="See you there">Get directions</AnimatedButton></div></div><div className="visit-details"><div><span>DOORS OPEN</span><p>Monday / 15:00<br/>Tuesday–Sunday / 10:00</p></div><div><span>FROM THE KITCHEN</span><p>Toasts until 14:00 · Eggs until 16:00<br/>Loaded fries & sides from 14:00</p><AnimatedButton href="/menu" variant="outline" hoverText="Take a look">Food & drinks</AnimatedButton></div></div></section>
  </main><SiteFooter/>
 </div>;
}
